---
- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: webapp, tags: webapp }
    - { role: nginx, tags: nginx }
    - { role: supervisor,   tags: supervisor }
    - { role: databases, tags: databases }

