---
- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: nginx, tags: nginx }
    - { role: databases, tags: databases }
    - { role: webapp, tags: webapp }

    - { role: supervisor,   tags: supervisor }
