# http://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# https://docs.travis-ci.com/user/languages/python

before_install:
  - sudo apt-get update -qq

language: python
python:
  - "2.7"

install:
  - "mv -v .env.sample .env"
  - "pip install ansible"
  - "pip install -r ohr/requirements/local.txt"
  - shopt -s expand_aliases
  - source bin/activate
  - ssh-keygen -f provision/id_rsa_ohr -N ""
  - configure_machines -l -s

script:
  - "m test oh users"
